#!/usr/bin/env python3
"""
第二轮数据补充：大幅增加中国抗日战争 & 苏联东线战场个体战役

中国方向（按Wikipedia/BaiduBaike）：
- 细分更多具体会战/战役
- 二战总死亡应达约 1500-2000 万级别

苏联方向（按Wikipedia/Britannica）：
- 东线主要战役缺失严重，仅 33 场 1260 万死亡
- 需补充斯大林格勒、库尔斯克、莫斯科、列宁格勒等核心战役
"""

import json, os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
BATTLE_JSON = os.path.join(BASE_DIR, '..', 'public', 'data', 'battle_events.json')

with open(BATTLE_JSON, 'r', encoding='utf-8') as f:
    existing = json.load(f)

max_id = max(e['id'] for e in existing)
nid = max(max_id + 1, 2001000)

print(f"Current: {len(existing)} battles, max ID: {max_id}, next ID: {nid}")

new_battles = [
    # ═══════════════ 中国抗日战争 - 细分战役 ═══════════════
    {
        "id": nid + 1,
        "name": "Marco Polo Bridge Incident",
        "war": "SECOND SINO-JAPANESE WAR",
        "warCn": "抗日战争",
        "sideA": "Japan",
        "sideB": "China",
        "latitude": 39.8484, "longitude": 116.2127,
        "date": "1937-07-07", "year": 1937, "winner": "defender",
        "region": "Asia", "country": "China",
        "attackerTroops": 5600, "defenderTroops": 100000,
        "totalTroops": 105600, "attackerCasualties": 660, "defenderCasualties": 16000,
        "totalCasualties": 16660, "casualtyRate": 0.1578,
        "terrain": "Urban, River Bridge",
        "weather": "Hot, Summer", "commanderA": "KANICHIRO TASHIRO", "commanderB": "SONG ZHEYUAN",
        "front": 20, "depth": 10,
        "wikiUrl": "https://en.wikipedia.org/wiki/Marco_Polo_Bridge_Incident",
        "attackerAllies": [], "defenderAllies": [], "source": "manual_enrich_china"
    },
    {
        "id": nid + 2,
        "name": "Battle of Beiping-Tianjin",
        "war": "SECOND SINO-JAPANESE WAR",
        "warCn": "抗日战争",
        "sideA": "Japan", "sideB": "China",
        "latitude": 39.1336, "longitude": 117.2054,
        "date": "1937-07-25", "year": 1937, "winner": "defender",
        "region": "Asia", "country": "China",
        "attackerTroops": 20000, "defenderTroops": 46000,
        "totalTroops": 66000, "attackerCasualties": 127, "defenderCasualties": 5000,
        "totalCasualties": 5127, "casualtyRate": 0.0777,
        "terrain": "Urban, River", "weather": "Hot, Summer",
        "commanderA": "KIYOSHI KATSUKI", "commanderB": "ZHANG ZIZHONG",
        "front": 50, "depth": 30,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Beiping%E2%80%93Tianjin",
        "attackerAllies": [], "defenderAllies": [], "source": "manual_enrich_china"
    },
    {
        "id": nid + 3,
        "name": "Battle of Xinkou",
        "war": "SECOND SINO-JAPANESE WAR",
        "warCn": "抗日战争",
        "sideA": "Japan", "sideB": "China",
        "latitude": 38.4643, "longitude": 112.7370,
        "date": "1937-10-13", "year": 1937, "winner": "attacker",
        "region": "Asia", "country": "China",
        "attackerTroops": 50000, "defenderTroops": 100000,
        "totalTroops": 150000, "attackerCasualties": 10000, "defenderCasualties": 100000,
        "totalCasualties": 110000, "casualtyRate": 0.7333,
        "terrain": "Mountain Pass, Rural",
        "weather": "Cool, Autumn", "commanderA": "ITAGAKI SEISHIRO", "commanderB": "WEI LIHUANG",
        "front": 50, "depth": 30,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Xinkou",
        "attackerAllies": [], "defenderAllies": [], "source": "manual_enrich_china"
    },
    {
        "id": nid + 4,
        "name": "Battle of Xuzhou",
        "war": "SECOND SINO-JAPANESE WAR",
        "warCn": "抗日战争",
        "sideA": "Japan", "sideB": "China",
        "latitude": 34.2619, "longitude": 117.1944,
        "date": "1937-12-01", "year": 1937, "winner": "defender",
        "region": "Asia", "country": "China",
        "attackerTroops": 240000, "defenderTroops": 600000,
        "totalTroops": 840000, "attackerCasualties": 30000, "defenderCasualties": 100000,
        "totalCasualties": 130000, "casualtyRate": 0.1548,
        "terrain": "Rural, Urban, Plain",
        "weather": "Cold, Winter", "commanderA": "SHUNROKU HATA", "commanderB": "LI ZONGREN",
        "front": 200, "depth": 150,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Xuzhou",
        "attackerAllies": [], "defenderAllies": [], "source": "manual_enrich_china"
    },
    {
        "id": nid + 5,
        "name": "Battle of Wanjialing",
        "war": "SECOND SINO-JAPANESE WAR",
        "warCn": "抗日战争",
        "sideA": "China", "sideB": "Japan",
        "latitude": 29.4000, "longitude": 115.8000,
        "date": "1938-10-01", "year": 1938, "winner": "attacker",
        "region": "Asia", "country": "China",
        "attackerTroops": 100000, "defenderTroops": 30000,
        "totalTroops": 130000, "attackerCasualties": 15000, "defenderCasualties": 30000,
        "totalCasualties": 45000, "casualtyRate": 0.3462,
        "terrain": "Mountain, Rural",
        "weather": "Mild, Autumn", "commanderA": "XUE YUE", "commanderB": "JUNROKURO MATSUURA",
        "front": 20, "depth": 15,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Wanjialing",
        "attackerAllies": [], "defenderAllies": [], "source": "manual_enrich_china"
    },
    {
        "id": nid + 6,
        "name": "Battle of Nanchang",
        "war": "SECOND SINO-JAPANESE WAR",
        "warCn": "抗日战争",
        "sideA": "Japan", "sideB": "China",
        "latitude": 28.6820, "longitude": 115.8579,
        "date": "1939-03-17", "year": 1939, "winner": "attacker",
        "region": "Asia", "country": "China",
        "attackerTroops": 120000, "defenderTroops": 200000,
        "totalTroops": 320000, "attackerCasualties": 24000, "defenderCasualties": 51000,
        "totalCasualties": 75000, "casualtyRate": 0.2344,
        "terrain": "River, Urban",
        "weather": "Mild, Spring", "commanderA": "YASUJI OKAMURA", "commanderB": "XUE YUE",
        "front": 80, "depth": 50,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Nanchang",
        "attackerAllies": [], "defenderAllies": [], "source": "manual_enrich_china"
    },
    {
        "id": nid + 7,
        "name": "Battle of Suixian-Zaoyang",
        "war": "SECOND SINO-JAPANESE WAR",
        "warCn": "抗日战争",
        "sideA": "Japan", "sideB": "China",
        "latitude": 31.8300, "longitude": 113.4600,
        "date": "1939-04-20", "year": 1939, "winner": "attacker",
        "region": "Asia", "country": "China",
        "attackerTroops": 113000, "defenderTroops": 220000,
        "totalTroops": 333000, "attackerCasualties": 13000, "defenderCasualties": 28000,
        "totalCasualties": 41000, "casualtyRate": 0.1231,
        "terrain": "Rural, Plain",
        "weather": "Mild, Spring", "commanderA": "YASUJI OKAMURA", "commanderB": "LI ZONGREN",
        "front": 100, "depth": 60,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Suixian%E2%80%93Zaoyang",
        "attackerAllies": [], "defenderAllies": [], "source": "manual_enrich_china"
    },
    {
        "id": nid + 8,
        "name": "Second Battle of Changsha",
        "war": "SECOND SINO-JAPANESE WAR",
        "warCn": "抗日战争",
        "sideA": "Japan", "sideB": "China",
        "latitude": 28.2282, "longitude": 112.9388,
        "date": "1941-09-06", "year": 1941, "winner": "attacker",
        "region": "Asia", "country": "China",
        "attackerTroops": 120000, "defenderTroops": 300000,
        "totalTroops": 420000, "attackerCasualties": 13700, "defenderCasualties": 50000,
        "totalCasualties": 63700, "casualtyRate": 0.1517,
        "terrain": "River, Urban, Mountain",
        "weather": "Hot, Late Summer", "commanderA": "KOREHIKO ANAMI", "commanderB": "XUE YUE",
        "front": 80, "depth": 60,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Changsha_(1941)",
        "attackerAllies": [], "defenderAllies": [], "source": "manual_enrich_china"
    },
    {
        "id": nid + 9,
        "name": "Third Battle of Changsha",
        "war": "SECOND SINO-JAPANESE WAR",
        "warCn": "抗日战争",
        "sideA": "Japan", "sideB": "China",
        "latitude": 28.2282, "longitude": 112.9388,
        "date": "1941-12-24", "year": 1941, "winner": "attacker",
        "region": "Asia", "country": "China",
        "attackerTroops": 120000, "defenderTroops": 300000,
        "totalTroops": 420000, "attackerCasualties": 56900, "defenderCasualties": 29000,
        "totalCasualties": 85900, "casualtyRate": 0.2045,
        "terrain": "River, Urban, Winter",
        "weather": "Cold, Winter", "commanderA": "KOREHIKO ANAMI", "commanderB": "XUE YUE",
        "front": 80, "depth": 60,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Changsha_(1942)",
        "attackerAllies": [], "defenderAllies": [], "source": "manual_enrich_china"
    },
    {
        "id": nid + 10,
        "name": "Battle of Zhejiang-Jiangxi",
        "war": "SECOND SINO-JAPANESE WAR",
        "warCn": "抗日战争",
        "sideA": "Japan", "sideB": "China",
        "latitude": 29.5000, "longitude": 119.0000,
        "date": "1942-05-15", "year": 1942, "winner": "attacker",
        "region": "Asia", "country": "China",
        "attackerTroops": 140000, "defenderTroops": 300000,
        "totalTroops": 440000, "attackerCasualties": 36000, "defenderCasualties": 70000,
        "totalCasualties": 106000, "casualtyRate": 0.2409,
        "terrain": "Rural, Mountain, River",
        "weather": "Hot, Humid", "commanderA": "SHUNROKU HATA", "commanderB": "GU ZHUTONG",
        "front": 300, "depth": 200,
        "wikiUrl": "https://en.wikipedia.org/wiki/Zhejiang-Jiangxi_campaign",
        "attackerAllies": [], "defenderAllies": [], "source": "manual_enrich_china"
    },
    {
        "id": nid + 11,
        "name": "Battle of West Hubei",
        "war": "SECOND SINO-JAPANESE WAR",
        "warCn": "抗日战争",
        "sideA": "Japan", "sideB": "China",
        "latitude": 30.5000, "longitude": 111.5000,
        "date": "1943-05-12", "year": 1943, "winner": "attacker",
        "region": "Asia", "country": "China",
        "attackerTroops": 100000, "defenderTroops": 200000,
        "totalTroops": 300000, "attackerCasualties": 25000, "defenderCasualties": 50000,
        "totalCasualties": 75000, "casualtyRate": 0.25,
        "terrain": "River, Mountain, Rural",
        "weather": "Mild, Spring", "commanderA": "ISAMU YOKOYAMA", "commanderB": "CHEN CHENG",
        "front": 100, "depth": 80,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_West_Hubei",
        "attackerAllies": [], "defenderAllies": [], "source": "manual_enrich_china"
    },
    {
        "id": nid + 12,
        "name": "Battle of Northern Burma and Western Yunnan",
        "war": "SECOND SINO-JAPANESE WAR",
        "warCn": "抗日战争",
        "sideA": "China", "sideB": "Japan",
        "latitude": 25.0000, "longitude": 98.0000,
        "date": "1943-10-01", "year": 1943, "winner": "attacker",
        "region": "Asia", "country": "China",
        "attackerTroops": 400000, "defenderTroops": 120000,
        "totalTroops": 520000, "attackerCasualties": 107000, "defenderCasualties": 50000,
        "totalCasualties": 157000, "casualtyRate": 0.3019,
        "terrain": "Jungle, Mountain, River",
        "weather": "Tropical, Monsoon", "commanderA": "WEI LIHUANG", "commanderB": "MASAKAZU KAWABE",
        "front": 200, "depth": 150,
        "wikiUrl": "https://en.wikipedia.org/wiki/Burma_campaign",
        "attackerAllies": ["United States", "United Kingdom"], "defenderAllies": [],
        "source": "manual_enrich_china"
    },
    {
        "id": nid + 13,
        "name": "Battle of Central Henan",
        "war": "SECOND SINO-JAPANESE WAR",
        "warCn": "抗日战争",
        "sideA": "Japan", "sideB": "China",
        "latitude": 34.7545, "longitude": 113.6622,
        "date": "1944-04-17", "year": 1944, "winner": "defender",
        "region": "Asia", "country": "China",
        "attackerTroops": 390000, "defenderTroops": 110000,
        "totalTroops": 500000, "attackerCasualties": 30000, "defenderCasualties": 200000,
        "totalCasualties": 230000, "casualtyRate": 0.46,
        "terrain": "Plain, Urban, Rural",
        "weather": "Mild, Spring", "commanderA": "SHUNROKU HATA", "commanderB": "TANG ENBO",
        "front": 200, "depth": 150,
        "wikiUrl": "https://en.wikipedia.org/wiki/Operation_Ichi-Go",
        "attackerAllies": [], "defenderAllies": [], "source": "manual_enrich_china"
    },
    {
        "id": nid + 14,
        "name": "Defense of Hengyang",
        "war": "SECOND SINO-JAPANESE WAR",
        "warCn": "抗日战争",
        "sideA": "Japan", "sideB": "China",
        "latitude": 26.8934, "longitude": 112.5718,
        "date": "1944-06-22", "year": 1944, "winner": "attacker",
        "region": "Asia", "country": "China",
        "attackerTroops": 110000, "defenderTroops": 17000,
        "totalTroops": 127000, "attackerCasualties": 40000, "defenderCasualties": 17000,
        "totalCasualties": 57000, "casualtyRate": 0.4488,
        "terrain": "Urban, Siege",
        "weather": "Hot, Humid", "commanderA": "ISAMU YOKOYAMA", "commanderB": "FANG XIANJUE",
        "front": 10, "depth": 8,
        "wikiUrl": "https://en.wikipedia.org/wiki/Defense_of_Hengyang",
        "attackerAllies": [], "defenderAllies": [], "source": "manual_enrich_china"
    },
    {
        "id": nid + 15,
        "name": "Battle of Guilin-Liuzhou",
        "war": "SECOND SINO-JAPANESE WAR",
        "warCn": "抗日战争",
        "sideA": "Japan", "sideB": "China",
        "latitude": 25.2750, "longitude": 110.2833,
        "date": "1944-08-16", "year": 1944, "winner": "defender",
        "region": "Asia", "country": "China",
        "attackerTroops": 400000, "defenderTroops": 160000,
        "totalTroops": 560000, "attackerCasualties": 30000, "defenderCasualties": 200000,
        "totalCasualties": 230000, "casualtyRate": 0.4107,
        "terrain": "Mountain, Urban, River",
        "weather": "Hot, Summer", "commanderA": "YASUJI OKAMURA", "commanderB": "BAI CHONGXI",
        "front": 200, "depth": 150,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Guilin%E2%80%93Liuzhou",
        "attackerAllies": [], "defenderAllies": [], "source": "manual_enrich_china"
    },

    # ═══════════════ 苏联东线战场 - 核心战役 ═══════════════
    {
        "id": nid + 20,
        "name": "Battle of Moscow",
        "war": "WORLD WAR II (EASTERN FRONT)",
        "warCn": "第二次世界大战",
        "sideA": "Germany", "sideB": "URSS",
        "latitude": 55.7512, "longitude": 37.6184,
        "date": "1941-10-02", "year": 1941, "winner": "defender",
        "region": "Europe", "country": "URSS",
        "attackerTroops": 1929406, "defenderTroops": 1252591,
        "totalTroops": 3181997, "attackerCasualties": 280000, "defenderCasualties": 1029376,
        "totalCasualties": 1309376, "casualtyRate": 0.4115,
        "terrain": "Urban, Rural, Winter",
        "weather": "Cold, Winter, Snow", "commanderA": "FEDOR VON BOCK", "commanderB": "GEORGY ZHUKOV",
        "front": 600, "depth": 200,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Moscow",
        "attackerAllies": [], "defenderAllies": [], "source": "manual_enrich_ussr"
    },
    {
        "id": nid + 21,
        "name": "Siege of Leningrad",
        "war": "WORLD WAR II (EASTERN FRONT)",
        "warCn": "第二次世界大战",
        "sideA": "Germany", "sideB": "URSS",
        "latitude": 59.9343, "longitude": 30.3351,
        "date": "1941-09-08", "year": 1941, "winner": "defender",
        "region": "Europe", "country": "URSS",
        "attackerTroops": 725000, "defenderTroops": 930000,
        "totalTroops": 1655000, "attackerCasualties": 500000, "defenderCasualties": 1100000,
        "totalCasualties": 1600000, "casualtyRate": 0.9668,
        "terrain": "Urban, Siege, Winter",
        "weather": "Cold, Starvation", "commanderA": "WILHELM VON LEEB", "commanderB": "GEORGY ZHUKOV",
        "front": 50, "depth": 30,
        "wikiUrl": "https://en.wikipedia.org/wiki/Siege_of_Leningrad",
        "attackerAllies": ["Finland"], "defenderAllies": [], "source": "manual_enrich_ussr"
    },
    {
        "id": nid + 22,
        "name": "Battle of Stalingrad",
        "war": "WORLD WAR II (EASTERN FRONT)",
        "warCn": "第二次世界大战",
        "sideA": "Germany", "sideB": "URSS",
        "latitude": 48.7080, "longitude": 44.5133,
        "date": "1942-08-23", "year": 1942, "winner": "defender",
        "region": "Europe", "country": "URSS",
        "attackerTroops": 1040000, "defenderTroops": 1143000,
        "totalTroops": 2183000, "attackerCasualties": 850000, "defenderCasualties": 1129619,
        "totalCasualties": 1979619, "casualtyRate": 0.9069,
        "terrain": "Urban, River, Winter, Ruins",
        "weather": "Cold, Winter", "commanderA": "FRIEDRICH PAULUS", "commanderB": "VASILY CHUIKOV",
        "front": 30, "depth": 20,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Stalingrad",
        "attackerAllies": ["Romania", "Italy", "Hungary"], "defenderAllies": [], "source": "manual_enrich_ussr"
    },
    {
        "id": nid + 23,
        "name": "Battle of Kursk",
        "war": "WORLD WAR II (EASTERN FRONT)",
        "warCn": "第二次世界大战",
        "sideA": "Germany", "sideB": "URSS",
        "latitude": 51.7333, "longitude": 36.1833,
        "date": "1943-07-05", "year": 1943, "winner": "defender",
        "region": "Europe", "country": "URSS",
        "attackerTroops": 780900, "defenderTroops": 1910361,
        "totalTroops": 2691261, "attackerCasualties": 200000, "defenderCasualties": 863303,
        "totalCasualties": 1063303, "casualtyRate": 0.3951,
        "terrain": "Plain, Rural, Summer",
        "weather": "Hot, Summer", "commanderA": "ERICH VON MANSTEIN", "commanderB": "GEORGY ZHUKOV",
        "front": 200, "depth": 150,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Kursk",
        "attackerAllies": [], "defenderAllies": [], "source": "manual_enrich_ussr"
    },
    {
        "id": nid + 24,
        "name": "Battle of Kiev (1941)",
        "war": "WORLD WAR II (EASTERN FRONT)",
        "warCn": "第二次世界大战",
        "sideA": "Germany", "sideB": "URSS",
        "latitude": 50.4501, "longitude": 30.5234,
        "date": "1941-08-23", "year": 1941, "winner": "attacker",
        "region": "Europe", "country": "URSS",
        "attackerTroops": 500000, "defenderTroops": 627000,
        "totalTroops": 1127000, "attackerCasualties": 128670, "defenderCasualties": 700544,
        "totalCasualties": 829214, "casualtyRate": 0.7358,
        "terrain": "Urban, Plain, Summer",
        "weather": "Warm, Summer", "commanderA": "GERD VON RUNDSTEDT", "commanderB": "SEMYON BUDYONNY",
        "front": 150, "depth": 100,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Kiev_(1941)",
        "attackerAllies": [], "defenderAllies": [], "source": "manual_enrich_ussr"
    },
    {
        "id": nid + 25,
        "name": "Second Battle of Kharkov",
        "war": "WORLD WAR II (EASTERN FRONT)",
        "warCn": "第二次世界大战",
        "sideA": "URSS", "sideB": "Germany",
        "latitude": 49.9935, "longitude": 36.2304,
        "date": "1942-05-12", "year": 1942, "winner": "defender",
        "region": "Europe", "country": "URSS",
        "attackerTroops": 765300, "defenderTroops": 350000,
        "totalTroops": 1115300, "attackerCasualties": 277190, "defenderCasualties": 20000,
        "totalCasualties": 297190, "casualtyRate": 0.2665,
        "terrain": "Plain, Urban",
        "weather": "Mild, Spring", "commanderA": "SEMYON TIMOSHENKO", "commanderB": "FRIEDRICH PAULUS",
        "front": 100, "depth": 60,
        "wikiUrl": "https://en.wikipedia.org/wiki/Second_Battle_of_Kharkov",
        "attackerAllies": [], "defenderAllies": [], "source": "manual_enrich_ussr"
    },
    {
        "id": nid + 26,
        "name": "Battle of Smolensk (1941)",
        "war": "WORLD WAR II (EASTERN FRONT)",
        "warCn": "第二次世界大战",
        "sideA": "Germany", "sideB": "URSS",
        "latitude": 54.7833, "longitude": 32.0500,
        "date": "1941-07-10", "year": 1941, "winner": "attacker",
        "region": "Europe", "country": "URSS",
        "attackerTroops": 430000, "defenderTroops": 581600,
        "totalTroops": 1011600, "attackerCasualties": 100000, "defenderCasualties": 759974,
        "totalCasualties": 859974, "casualtyRate": 0.8501,
        "terrain": "Urban, Rural, Summer",
        "weather": "Warm, Summer", "commanderA": "HEINZ GUDERIAN", "commanderB": "SEMYON TIMOSHENKO",
        "front": 200, "depth": 150,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Smolensk_(1941)",
        "attackerAllies": [], "defenderAllies": [], "source": "manual_enrich_ussr"
    },
    {
        "id": nid + 27,
        "name": "Siege of Sevastopol",
        "war": "WORLD WAR II (EASTERN FRONT)",
        "warCn": "第二次世界大战",
        "sideA": "Germany", "sideB": "URSS",
        "latitude": 44.6167, "longitude": 33.5254,
        "date": "1941-10-30", "year": 1941, "winner": "attacker",
        "region": "Europe", "country": "URSS",
        "attackerTroops": 203800, "defenderTroops": 118000,
        "totalTroops": 321800, "attackerCasualties": 76000, "defenderCasualties": 95000,
        "totalCasualties": 171000, "casualtyRate": 0.5314,
        "terrain": "Coastal, Fortress, Siege",
        "weather": "Mild, Coastal", "commanderA": "ERICH VON MANSTEIN", "commanderB": "IVAN PETROV",
        "front": 20, "depth": 15,
        "wikiUrl": "https://en.wikipedia.org/wiki/Siege_of_Sevastopol_(1941%E2%80%931942)",
        "attackerAllies": ["Romania"], "defenderAllies": [], "source": "manual_enrich_ussr"
    },
    {
        "id": nid + 28,
        "name": "Operation Bagration",
        "war": "WORLD WAR II (EASTERN FRONT)",
        "warCn": "第二次世界大战",
        "sideA": "URSS", "sideB": "Germany",
        "latitude": 53.9000, "longitude": 27.5667,
        "date": "1944-06-22", "year": 1944, "winner": "attacker",
        "region": "Europe", "country": "URSS",
        "attackerTroops": 2337000, "defenderTroops": 486493,
        "totalTroops": 2823493, "attackerCasualties": 180040, "defenderCasualties": 399102,
        "totalCasualties": 579142, "casualtyRate": 0.2051,
        "terrain": "Forest, Swamp, Rural",
        "weather": "Mild, Summer", "commanderA": "KONSTANTIN ROKOSSOVSKY", "commanderB": "ERNST BUSCH",
        "front": 600, "depth": 400,
        "wikiUrl": "https://en.wikipedia.org/wiki/Operation_Bagration",
        "attackerAllies": [], "defenderAllies": [], "source": "manual_enrich_ussr"
    },
    {
        "id": nid + 29,
        "name": "Battle of Berlin",
        "war": "WORLD WAR II (EASTERN FRONT)",
        "warCn": "第二次世界大战",
        "sideA": "URSS", "sideB": "Germany",
        "latitude": 52.5200, "longitude": 13.4050,
        "date": "1945-04-16", "year": 1945, "winner": "attacker",
        "region": "Europe", "country": "URSS",
        "attackerTroops": 2500000, "defenderTroops": 766750,
        "totalTroops": 3266750, "attackerCasualties": 361367, "defenderCasualties": 458080,
        "totalCasualties": 819447, "casualtyRate": 0.2508,
        "terrain": "Urban, Siege, Ruins",
        "weather": "Mild, Spring", "commanderA": "GEORGY ZHUKOV", "commanderB": "GOTTHARD HEINRICI",
        "front": 100, "depth": 50,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Berlin",
        "attackerAllies": ["Poland"], "defenderAllies": [], "source": "manual_enrich_ussr"
    },
    {
        "id": nid + 30,
        "name": "Operation Uranus",
        "war": "WORLD WAR II (EASTERN FRONT)",
        "warCn": "第二次世界大战",
        "sideA": "URSS", "sideB": "Germany",
        "latitude": 48.7080, "longitude": 44.5133,
        "date": "1942-11-19", "year": 1942, "winner": "attacker",
        "region": "Europe", "country": "URSS",
        "attackerTroops": 1143500, "defenderTroops": 600000,
        "totalTroops": 1743500, "attackerCasualties": 154885, "defenderCasualties": 400000,
        "totalCasualties": 554885, "casualtyRate": 0.3183,
        "terrain": "Plain, Winter, Snow",
        "weather": "Cold, Winter", "commanderA": "GEORGY ZHUKOV", "commanderB": "FRIEDRICH PAULUS",
        "front": 150, "depth": 100,
        "wikiUrl": "https://en.wikipedia.org/wiki/Operation_Uranus",
        "attackerAllies": [], "defenderAllies": ["Romania", "Italy"], "source": "manual_enrich_ussr"
    },
    {
        "id": nid + 31,
        "name": "Battle of Bryansk",
        "war": "WORLD WAR II (EASTERN FRONT)",
        "warCn": "第二次世界大战",
        "sideA": "Germany", "sideB": "URSS",
        "latitude": 53.2500, "longitude": 34.3667,
        "date": "1941-09-30", "year": 1941, "winner": "attacker",
        "region": "Europe", "country": "URSS",
        "attackerTroops": 929406, "defenderTroops": 260000,
        "totalTroops": 1189406, "attackerCasualties": 45000, "defenderCasualties": 200000,
        "totalCasualties": 245000, "casualtyRate": 0.206,
        "terrain": "Forest, Rural",
        "weather": "Cool, Autumn", "commanderA": "HEINZ GUDERIAN", "commanderB": "ANDREI YERYOMENKO",
        "front": 150, "depth": 100,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Bryansk",
        "attackerAllies": [], "defenderAllies": [], "source": "manual_enrich_ussr"
    },
    {
        "id": nid + 32,
        "name": "Battle of the Dnieper",
        "war": "WORLD WAR II (EASTERN FRONT)",
        "warCn": "第二次世界大战",
        "sideA": "URSS", "sideB": "Germany",
        "latitude": 50.4333, "longitude": 30.5167,
        "date": "1943-08-26", "year": 1943, "winner": "attacker",
        "region": "Europe", "country": "URSS",
        "attackerTroops": 2650000, "defenderTroops": 1250000,
        "totalTroops": 3900000, "attackerCasualties": 417323, "defenderCasualties": 300000,
        "totalCasualties": 717323, "casualtyRate": 0.1839,
        "terrain": "River Crossing, Plain, Rural",
        "weather": "Mild, Autumn", "commanderA": "KONSTANTIN ROKOSSOVSKY", "commanderB": "ERICH VON MANSTEIN",
        "front": 400, "depth": 300,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_the_Dnieper",
        "attackerAllies": [], "defenderAllies": [], "source": "manual_enrich_ussr"
    },
]

# =========== Append and save ===========
existing.extend(new_battles)

with open(BATTLE_JSON, 'w', encoding='utf-8') as f:
    json.dump(existing, f, ensure_ascii=False, indent=2)

print(f"\nAdded {len(new_battles)} battles ({len([x for x in new_battles if x['source']=='manual_enrich_china'])} China, {len([x for x in new_battles if x['source']=='manual_enrich_ussr'])} USSR)")

# Summary
for src in ['manual_enrich_china', 'manual_enrich_ussr']:
    src_battles = [x for x in new_battles if x['source'] == src]
    deaths = sum(x['totalCasualties'] for x in src_battles)
    print(f"  {src}: {len(src_battles)} battles, {deaths:,} deaths")

# Overall China and USSR deaths
all_battles = existing
china_deaths = sum(e['totalCasualties'] for e in all_battles if e['country'] == 'China')
ussr_deaths = sum(e['totalCasualties'] for e in all_battles if e['country'] in ('URSS', 'Russia'))
print(f"\nOverall China deaths: {china_deaths:,}")
print(f"Overall USSR deaths: {ussr_deaths:,}")
print(f"Total battles: {len(all_battles)}")
