#!/usr/bin/env python3
"""
补充中国历史战役数据，主要包括：
- 抗日战争 (Second Sino-Japanese War, 1937-1945)
- 太平天国运动 (Taiping Rebellion, 1850-1864)  
- 中日甲午战争 (First Sino-Japanese War, 1894-1895)
- 鸦片战争 (Opium Wars, 1840-1860)
- 国共内战三大战役 (Chinese Civil War, 1948-1949)
- 八国联军侵华 (Boxer Rebellion, 1900)

数据来源：Wikipedia, Baidu Baike, Britannica
"""

import json
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
BATTLE_JSON = os.path.join(BASE_DIR, '..', 'public', 'data', 'battle_events.json')

# Load existing data
with open(BATTLE_JSON, 'r', encoding='utf-8') as f:
    existing_data = json.load(f)

max_id = max(e['id'] for e in existing_data)
next_id = max(max_id + 1, 2000500)

print(f"Existing battles: {len(existing_data)}, max ID: {max_id}, next ID: {next_id}")

# ============== 新增中国战役数据 ==============
china_battles = [
    # ═══════════ 抗日战争 (Second Sino-Japanese War, 1937-1945) ═══════════
    {
        "id": next_id + 1,
        "name": "Battle of Shanghai",
        "war": "SECOND SINO-JAPANESE WAR",
        "warCn": "抗日战争",
        "sideA": "China",
        "sideB": "Japan",
        "latitude": 31.2304,
        "longitude": 121.4737,
        "date": "1937-08-13",
        "year": 1937,
        "winner": "defender",
        "region": "Asia",
        "country": "China",
        "attackerTroops": 750000,
        "defenderTroops": 300000,
        "totalTroops": 1050000,
        "attackerCasualties": 250000,
        "defenderCasualties": 40000,
        "totalCasualties": 290000,
        "casualtyRate": 0.2762,
        "terrain": "Urban, Coastal",
        "weather": "Hot, Humid, Summer",
        "commanderA": "CHIANG KAI-SHEK",
        "commanderB": "IWANE MATSUI",
        "front": 200,
        "depth": 50,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Shanghai",
        "attackerAllies": [],
        "defenderAllies": [],
        "source": "manual_enrich_china"
    },
    {
        "id": next_id + 2,
        "name": "Battle of Nanjing",
        "war": "SECOND SINO-JAPANESE WAR",
        "warCn": "抗日战争",
        "sideA": "China",
        "sideB": "Japan",
        "latitude": 32.0603,
        "longitude": 118.7969,
        "date": "1937-12-01",
        "year": 1937,
        "winner": "defender",
        "region": "Asia",
        "country": "China",
        "attackerTroops": 100000,
        "defenderTroops": 200000,
        "totalTroops": 300000,
        "attackerCasualties": 50000,
        "defenderCasualties": 6000,
        "totalCasualties": 356000,
        "casualtyRate": 1.1867,
        "terrain": "Urban, River",
        "weather": "Cold, Winter",
        "commanderA": "TANG SHENGZHI",
        "commanderB": "IWANE MATSUI",
        "front": 50,
        "depth": 30,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Nanking",
        "attackerAllies": [],
        "defenderAllies": [],
        "source": "manual_enrich_china"
    },
    {
        "id": next_id + 3,
        "name": "Battle of Pingxingguan",
        "war": "SECOND SINO-JAPANESE WAR",
        "warCn": "抗日战争",
        "sideA": "China",
        "sideB": "Japan",
        "latitude": 39.3394,
        "longitude": 113.9444,
        "date": "1937-09-25",
        "year": 1937,
        "winner": "attacker",
        "region": "Asia",
        "country": "China",
        "attackerTroops": 6000,
        "defenderTroops": 4000,
        "totalTroops": 10000,
        "attackerCasualties": 400,
        "defenderCasualties": 1000,
        "totalCasualties": 1400,
        "casualtyRate": 0.14,
        "terrain": "Mountain Pass",
        "weather": "Cool, Autumn",
        "commanderA": "LIN BIAO",
        "commanderB": "ITAGAKI SEISHIRO",
        "front": 10,
        "depth": 5,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Pingxingguan",
        "attackerAllies": ["Chinese Communist Party"],
        "defenderAllies": [],
        "source": "manual_enrich_china"
    },
    {
        "id": next_id + 4,
        "name": "Battle of Taierzhuang",
        "war": "SECOND SINO-JAPANESE WAR",
        "warCn": "抗日战争",
        "sideA": "China",
        "sideB": "Japan",
        "latitude": 34.5572,
        "longitude": 117.7344,
        "date": "1938-03-24",
        "year": 1938,
        "winner": "attacker",
        "region": "Asia",
        "country": "China",
        "attackerTroops": 100000,
        "defenderTroops": 30000,
        "totalTroops": 130000,
        "attackerCasualties": 20000,
        "defenderCasualties": 16000,
        "totalCasualties": 36000,
        "casualtyRate": 0.2769,
        "terrain": "Urban, Rural",
        "weather": "Mild, Spring",
        "commanderA": "LI ZONGREN",
        "commanderB": "RENSUKE ISOGAI",
        "front": 30,
        "depth": 20,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Taierzhuang",
        "attackerAllies": [],
        "defenderAllies": [],
        "source": "manual_enrich_china"
    },
    {
        "id": next_id + 5,
        "name": "Battle of Wuhan",
        "war": "SECOND SINO-JAPANESE WAR",
        "warCn": "抗日战争",
        "sideA": "China",
        "sideB": "Japan",
        "latitude": 30.5928,
        "longitude": 114.3055,
        "date": "1938-06-11",
        "year": 1938,
        "winner": "defender",
        "region": "Asia",
        "country": "China",
        "attackerTroops": 1100000,
        "defenderTroops": 350000,
        "totalTroops": 1450000,
        "attackerCasualties": 400000,
        "defenderCasualties": 140000,
        "totalCasualties": 540000,
        "casualtyRate": 0.3724,
        "terrain": "Rural, River, Urban",
        "weather": "Hot, Humid, Summer",
        "commanderA": "CHIANG KAI-SHEK",
        "commanderB": "SHUNROKU HATA",
        "front": 400,
        "depth": 200,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Wuhan",
        "attackerAllies": [],
        "defenderAllies": [],
        "source": "manual_enrich_china"
    },
    {
        "id": next_id + 6,
        "name": "First Battle of Changsha",
        "war": "SECOND SINO-JAPANESE WAR",
        "warCn": "抗日战争",
        "sideA": "China",
        "sideB": "Japan",
        "latitude": 28.2282,
        "longitude": 112.9388,
        "date": "1939-09-17",
        "year": 1939,
        "winner": "attacker",
        "region": "Asia",
        "country": "China",
        "attackerTroops": 180000,
        "defenderTroops": 100000,
        "totalTroops": 280000,
        "attackerCasualties": 30000,
        "defenderCasualties": 30000,
        "totalCasualties": 60000,
        "casualtyRate": 0.2143,
        "terrain": "River, Urban",
        "weather": "Mild, Autumn",
        "commanderA": "XUE YUE",
        "commanderB": "YASUJI OKAMURA",
        "front": 100,
        "depth": 80,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Changsha_(1939)",
        "attackerAllies": [],
        "defenderAllies": [],
        "source": "manual_enrich_china"
    },
    {
        "id": next_id + 7,
        "name": "Battle of Kunlun Pass",
        "war": "SECOND SINO-JAPANESE WAR",
        "warCn": "抗日战争",
        "sideA": "China",
        "sideB": "Japan",
        "latitude": 23.0833,
        "longitude": 108.6000,
        "date": "1939-12-18",
        "year": 1939,
        "winner": "attacker",
        "region": "Asia",
        "country": "China",
        "attackerTroops": 50000,
        "defenderTroops": 5000,
        "totalTroops": 55000,
        "attackerCasualties": 14000,
        "defenderCasualties": 4000,
        "totalCasualties": 18000,
        "casualtyRate": 0.3273,
        "terrain": "Mountain Pass",
        "weather": "Cool, Winter",
        "commanderA": "BAI CHONGXI",
        "commanderB": "MASAO NAKAMURA",
        "front": 15,
        "depth": 10,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Kunlun_Pass",
        "attackerAllies": [],
        "defenderAllies": [],
        "source": "manual_enrich_china"
    },
    {
        "id": next_id + 8,
        "name": "Hundred Regiments Offensive",
        "war": "SECOND SINO-JAPANESE WAR",
        "warCn": "抗日战争",
        "sideA": "China",
        "sideB": "Japan",
        "latitude": 37.8700,
        "longitude": 112.5500,
        "date": "1940-08-20",
        "year": 1940,
        "winner": "attacker",
        "region": "Asia",
        "country": "China",
        "attackerTroops": 400000,
        "defenderTroops": 300000,
        "totalTroops": 700000,
        "attackerCasualties": 22000,
        "defenderCasualties": 20000,
        "totalCasualties": 42000,
        "casualtyRate": 0.06,
        "terrain": "Rural, Railway",
        "weather": "Hot, Summer",
        "commanderA": "PENG DEHUAI",
        "commanderB": "HAYATAO TADA",
        "front": 500,
        "depth": 200,
        "wikiUrl": "https://en.wikipedia.org/wiki/Hundred_Regiments_Offensive",
        "attackerAllies": ["Chinese Communist Party"],
        "defenderAllies": [],
        "source": "manual_enrich_china"
    },
    {
        "id": next_id + 9,
        "name": "Battle of Changde",
        "war": "SECOND SINO-JAPANESE WAR",
        "warCn": "抗日战争",
        "sideA": "China",
        "sideB": "Japan",
        "latitude": 29.0396,
        "longitude": 111.6939,
        "date": "1943-11-02",
        "year": 1943,
        "winner": "attacker",
        "region": "Asia",
        "country": "China",
        "attackerTroops": 100000,
        "defenderTroops": 60000,
        "totalTroops": 160000,
        "attackerCasualties": 40000,
        "defenderCasualties": 30000,
        "totalCasualties": 70000,
        "casualtyRate": 0.4375,
        "terrain": "Urban, River",
        "weather": "Cold, Winter",
        "commanderA": "SUN LIANZHONG",
        "commanderB": "ISAMU YOKOYAMA",
        "front": 50,
        "depth": 30,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Changde",
        "attackerAllies": [],
        "defenderAllies": [],
        "source": "manual_enrich_china"
    },
    {
        "id": next_id + 10,
        "name": "Operation Ichi-Go",
        "war": "SECOND SINO-JAPANESE WAR",
        "warCn": "抗日战争",
        "sideA": "China",
        "sideB": "Japan",
        "latitude": 34.3416,
        "longitude": 113.5777,
        "date": "1944-04-17",
        "year": 1944,
        "winner": "defender",
        "region": "Asia",
        "country": "China",
        "attackerTroops": 400000,
        "defenderTroops": 500000,
        "totalTroops": 900000,
        "attackerCasualties": 380000,
        "defenderCasualties": 70000,
        "totalCasualties": 450000,
        "casualtyRate": 0.5,
        "terrain": "Rural, Urban, Railway",
        "weather": "Hot, Humid",
        "commanderA": "CHIANG KAI-SHEK",
        "commanderB": "SHUNROKU HATA",
        "front": 800,
        "depth": 400,
        "wikiUrl": "https://en.wikipedia.org/wiki/Operation_Ichi-Go",
        "attackerAllies": [],
        "defenderAllies": [],
        "source": "manual_enrich_china"
    },
    {
        "id": next_id + 11,
        "name": "Battle of West Hunan",
        "war": "SECOND SINO-JAPANESE WAR",
        "warCn": "抗日战争",
        "sideA": "China",
        "sideB": "Japan",
        "latitude": 28.0000,
        "longitude": 110.0000,
        "date": "1945-04-09",
        "year": 1945,
        "winner": "attacker",
        "region": "Asia",
        "country": "China",
        "attackerTroops": 110000,
        "defenderTroops": 80000,
        "totalTroops": 190000,
        "attackerCasualties": 20000,
        "defenderCasualties": 25000,
        "totalCasualties": 45000,
        "casualtyRate": 0.2368,
        "terrain": "Mountain, Rural",
        "weather": "Mild, Spring",
        "commanderA": "HE YINGQIN",
        "commanderB": "MATSUI ICHIRO",
        "front": 150,
        "depth": 80,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_West_Hunan",
        "attackerAllies": [],
        "defenderAllies": [],
        "source": "manual_enrich_china"
    },

    # ═══════════ 国共内战三大战役 (Chinese Civil War, 1947-1949) ═══════════
    {
        "id": next_id + 12,
        "name": "Menglianggu Campaign",
        "war": "CHINESE CIVIL WAR",
        "warCn": "中国内战",
        "sideA": "Chinese Communist Party",
        "sideB": "Kuomintang",
        "latitude": 35.6617,
        "longitude": 118.2477,
        "date": "1947-05-13",
        "year": 1947,
        "winner": "attacker",
        "region": "Asia",
        "country": "China",
        "attackerTroops": 270000,
        "defenderTroops": 450000,
        "totalTroops": 720000,
        "attackerCasualties": 12000,
        "defenderCasualties": 32000,
        "totalCasualties": 44000,
        "casualtyRate": 0.0611,
        "terrain": "Mountain, Rural",
        "weather": "Mild, Spring",
        "commanderA": "CHEN YI",
        "commanderB": "ZHANG LINGFU",
        "front": 100,
        "depth": 50,
        "wikiUrl": "https://en.wikipedia.org/wiki/Menglianggu_campaign",
        "attackerAllies": [],
        "defenderAllies": [],
        "source": "manual_enrich_china"
    },
    {
        "id": next_id + 13,
        "name": "Battle of Jinan",
        "war": "CHINESE CIVIL WAR",
        "warCn": "中国内战",
        "sideA": "Chinese Communist Party",
        "sideB": "Kuomintang",
        "latitude": 36.6683,
        "longitude": 116.9972,
        "date": "1948-09-16",
        "year": 1948,
        "winner": "attacker",
        "region": "Asia",
        "country": "China",
        "attackerTroops": 140000,
        "defenderTroops": 100000,
        "totalTroops": 240000,
        "attackerCasualties": 26000,
        "defenderCasualties": 84000,
        "totalCasualties": 110000,
        "casualtyRate": 0.4583,
        "terrain": "Urban, Siege",
        "weather": "Mild, Autumn",
        "commanderA": "SU YU",
        "commanderB": "WANG YAOWU",
        "front": 20,
        "depth": 15,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Jinan",
        "attackerAllies": [],
        "defenderAllies": [],
        "source": "manual_enrich_china"
    },
    {
        "id": next_id + 14,
        "name": "Liaoshen Campaign",
        "war": "CHINESE CIVIL WAR",
        "warCn": "中国内战",
        "sideA": "Chinese Communist Party",
        "sideB": "Kuomintang",
        "latitude": 41.8057,
        "longitude": 123.4315,
        "date": "1948-09-12",
        "year": 1948,
        "winner": "attacker",
        "region": "Asia",
        "country": "China",
        "attackerTroops": 700000,
        "defenderTroops": 550000,
        "totalTroops": 1250000,
        "attackerCasualties": 69000,
        "defenderCasualties": 472000,
        "totalCasualties": 541000,
        "casualtyRate": 0.4328,
        "terrain": "Urban, Rural, Winter",
        "weather": "Cold, Winter",
        "commanderA": "LIN BIAO",
        "commanderB": "WEI LIHUANG",
        "front": 500,
        "depth": 300,
        "wikiUrl": "https://en.wikipedia.org/wiki/Liaoshen_campaign",
        "attackerAllies": [],
        "defenderAllies": [],
        "source": "manual_enrich_china"
    },
    {
        "id": next_id + 15,
        "name": "Huaihai Campaign",
        "war": "CHINESE CIVIL WAR",
        "warCn": "中国内战",
        "sideA": "Chinese Communist Party",
        "sideB": "Kuomintang",
        "latitude": 34.2619,
        "longitude": 117.1944,
        "date": "1948-11-06",
        "year": 1948,
        "winner": "attacker",
        "region": "Asia",
        "country": "China",
        "attackerTroops": 600000,
        "defenderTroops": 800000,
        "totalTroops": 1400000,
        "attackerCasualties": 134000,
        "defenderCasualties": 555000,
        "totalCasualties": 689000,
        "casualtyRate": 0.4921,
        "terrain": "Rural, Urban, Plain",
        "weather": "Cold, Winter",
        "commanderA": "SU YU",
        "commanderB": "LIU ZHI",
        "front": 400,
        "depth": 300,
        "wikiUrl": "https://en.wikipedia.org/wiki/Huaihai_campaign",
        "attackerAllies": ["Chinese Communist Party"],
        "defenderAllies": ["United States"],
        "source": "manual_enrich_china"
    },
    {
        "id": next_id + 16,
        "name": "Pingjin Campaign",
        "war": "CHINESE CIVIL WAR",
        "warCn": "中国内战",
        "sideA": "Chinese Communist Party",
        "sideB": "Kuomintang",
        "latitude": 39.9042,
        "longitude": 116.4074,
        "date": "1948-11-29",
        "year": 1948,
        "winner": "attacker",
        "region": "Asia",
        "country": "China",
        "attackerTroops": 1000000,
        "defenderTroops": 520000,
        "totalTroops": 1520000,
        "attackerCasualties": 39000,
        "defenderCasualties": 520000,
        "totalCasualties": 559000,
        "casualtyRate": 0.3678,
        "terrain": "Urban, Rural, Winter",
        "weather": "Cold, Winter",
        "commanderA": "LIN BIAO",
        "commanderB": "FU ZUOYI",
        "front": 300,
        "depth": 200,
        "wikiUrl": "https://en.wikipedia.org/wiki/Pingjin_campaign",
        "attackerAllies": ["Chinese Communist Party"],
        "defenderAllies": [],
        "source": "manual_enrich_china"
    },
    {
        "id": next_id + 17,
        "name": "Yangtze River Crossing Campaign",
        "war": "CHINESE CIVIL WAR",
        "warCn": "中国内战",
        "sideA": "Chinese Communist Party",
        "sideB": "Kuomintang",
        "latitude": 32.0603,
        "longitude": 118.7969,
        "date": "1949-04-20",
        "year": 1949,
        "winner": "attacker",
        "region": "Asia",
        "country": "China",
        "attackerTroops": 1000000,
        "defenderTroops": 700000,
        "totalTroops": 1700000,
        "attackerCasualties": 45000,
        "defenderCasualties": 300000,
        "totalCasualties": 345000,
        "casualtyRate": 0.2029,
        "terrain": "River Crossing, Urban",
        "weather": "Mild, Spring",
        "commanderA": "LIU BOCHENG",
        "commanderB": "TANG ENBO",
        "front": 500,
        "depth": 100,
        "wikiUrl": "https://en.wikipedia.org/wiki/Yangtze_River_Crossing_campaign",
        "attackerAllies": [],
        "defenderAllies": [],
        "source": "manual_enrich_china"
    },

    # ═══════════ 太平天国 (Taiping Rebellion, 1850-1864) ═══════════
    {
        "id": next_id + 18,
        "name": "Siege of Nanjing",
        "war": "TAIPING REBELLION",
        "warCn": "太平天国",
        "sideA": "Taiping Heavenly Kingdom",
        "sideB": "Qing Dynasty",
        "latitude": 32.0603,
        "longitude": 118.7969,
        "date": "1853-03-19",
        "year": 1853,
        "winner": "attacker",
        "region": "Asia",
        "country": "China",
        "attackerTroops": 500000,
        "defenderTroops": 70000,
        "totalTroops": 570000,
        "attackerCasualties": 35000,
        "defenderCasualties": 70000,
        "totalCasualties": 105000,
        "casualtyRate": 0.1842,
        "terrain": "Urban, Siege, River",
        "weather": "Mild, Spring",
        "commanderA": "HONG XIUQUAN",
        "commanderB": "LU JIANYING",
        "front": 20,
        "depth": 15,
        "wikiUrl": "https://en.wikipedia.org/wiki/Taiping_Rebellion",
        "attackerAllies": [],
        "defenderAllies": [],
        "source": "manual_enrich_china"
    },
    {
        "id": next_id + 19,
        "name": "Battle of Anqing",
        "war": "TAIPING REBELLION",
        "warCn": "太平天国",
        "sideA": "Taiping Heavenly Kingdom",
        "sideB": "Qing Dynasty",
        "latitude": 30.5155,
        "longitude": 117.0389,
        "date": "1861-04-01",
        "year": 1861,
        "winner": "defender",
        "region": "Asia",
        "country": "China",
        "attackerTroops": 100000,
        "defenderTroops": 60000,
        "totalTroops": 160000,
        "attackerCasualties": 80000,
        "defenderCasualties": 20000,
        "totalCasualties": 100000,
        "casualtyRate": 0.625,
        "terrain": "River, Urban, Siege",
        "weather": "Mild, Spring",
        "commanderA": "CHEN YUCHENG",
        "commanderB": "ZENG GUOFAN",
        "front": 30,
        "depth": 20,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Anqing",
        "attackerAllies": [],
        "defenderAllies": [],
        "source": "manual_enrich_china"
    },
    {
        "id": next_id + 20,
        "name": "Third Battle of Nanjing",
        "war": "TAIPING REBELLION",
        "warCn": "太平天国",
        "sideA": "Qing Dynasty",
        "sideB": "Taiping Heavenly Kingdom",
        "latitude": 32.0603,
        "longitude": 118.7969,
        "date": "1864-03-14",
        "year": 1864,
        "winner": "attacker",
        "region": "Asia",
        "country": "China",
        "attackerTroops": 120000,
        "defenderTroops": 30000,
        "totalTroops": 150000,
        "attackerCasualties": 20000,
        "defenderCasualties": 100000,
        "totalCasualties": 120000,
        "casualtyRate": 0.8,
        "terrain": "Urban, Siege",
        "weather": "Mild, Spring",
        "commanderA": "ZENG GUOQUAN",
        "commanderB": "LI XIUCHENG",
        "front": 15,
        "depth": 10,
        "wikiUrl": "https://en.wikipedia.org/wiki/Third_Battle_of_Nanking",
        "attackerAllies": [],
        "defenderAllies": [],
        "source": "manual_enrich_china"
    },

    # ═══════════ 中日甲午战争 (First Sino-Japanese War, 1894-1895) ═══════════
    {
        "id": next_id + 21,
        "name": "Battle of the Yalu River",
        "war": "FIRST SINO-JAPANESE WAR",
        "warCn": "中日甲午战争",
        "sideA": "Qing Dynasty",
        "sideB": "Japan",
        "latitude": 39.5000,
        "longitude": 123.5000,
        "date": "1894-09-17",
        "year": 1894,
        "winner": "defender",
        "region": "Asia",
        "country": "China",
        "attackerTroops": 15000,
        "defenderTroops": 11000,
        "totalTroops": 26000,
        "attackerCasualties": 10000,
        "defenderCasualties": 1000,
        "totalCasualties": 11000,
        "casualtyRate": 0.4231,
        "terrain": "Naval, Coastal",
        "weather": "Mild, Autumn",
        "commanderA": "DING RUCHANG",
        "commanderB": "ITO SUKIYUKI",
        "front": 30,
        "depth": 20,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_the_Yalu_River_(1894)",
        "attackerAllies": [],
        "defenderAllies": [],
        "source": "manual_enrich_china"
    },
    {
        "id": next_id + 22,
        "name": "Battle of Weihaiwei",
        "war": "FIRST SINO-JAPANESE WAR",
        "warCn": "中日甲午战争",
        "sideA": "Qing Dynasty",
        "sideB": "Japan",
        "latitude": 37.5078,
        "longitude": 122.1222,
        "date": "1895-01-20",
        "year": 1895,
        "winner": "defender",
        "region": "Asia",
        "country": "China",
        "attackerTroops": 20000,
        "defenderTroops": 15000,
        "totalTroops": 35000,
        "attackerCasualties": 2000,
        "defenderCasualties": 4000,
        "totalCasualties": 6000,
        "casualtyRate": 0.1714,
        "terrain": "Coastal, Naval, Fortress",
        "weather": "Cold, Winter",
        "commanderA": "DING RUCHANG",
        "commanderB": "OYAMA IWAO",
        "front": 20,
        "depth": 15,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Weihaiwei",
        "attackerAllies": [],
        "defenderAllies": [],
        "source": "manual_enrich_china"
    },

    # ═══════════ 鸦片战争 (Opium Wars) ═══════════
    {
        "id": next_id + 23,
        "name": "Battle of the Bogue",
        "war": "FIRST OPIUM WAR",
        "warCn": "第一次鸦片战争",
        "sideA": "Qing Dynasty",
        "sideB": "United Kingdom",
        "latitude": 22.7833,
        "longitude": 113.6333,
        "date": "1841-02-26",
        "year": 1841,
        "winner": "defender",
        "region": "Asia",
        "country": "China",
        "attackerTroops": 8000,
        "defenderTroops": 1500,
        "totalTroops": 9500,
        "attackerCasualties": 3000,
        "defenderCasualties": 50,
        "totalCasualties": 3050,
        "casualtyRate": 0.3211,
        "terrain": "Coastal, Fortress",
        "weather": "Mild, Winter",
        "commanderA": "GUAN TIANPEI",
        "commanderB": "GORDON BREMER",
        "front": 10,
        "depth": 5,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_the_Bogue",
        "attackerAllies": [],
        "defenderAllies": [],
        "source": "manual_enrich_china"
    },
    {
        "id": next_id + 24,
        "name": "Battle of Chinkiang",
        "war": "FIRST OPIUM WAR",
        "warCn": "第一次鸦片战争",
        "sideA": "Qing Dynasty",
        "sideB": "United Kingdom",
        "latitude": 32.2000,
        "longitude": 119.4333,
        "date": "1842-07-21",
        "year": 1842,
        "winner": "defender",
        "region": "Asia",
        "country": "China",
        "attackerTroops": 8000,
        "defenderTroops": 7000,
        "totalTroops": 15000,
        "attackerCasualties": 3000,
        "defenderCasualties": 100,
        "totalCasualties": 3100,
        "casualtyRate": 0.2067,
        "terrain": "River, Urban",
        "weather": "Hot, Summer",
        "commanderA": "HAILING",
        "commanderB": "HUGH GOUGH",
        "front": 8,
        "depth": 5,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Chinkiang",
        "attackerAllies": [],
        "defenderAllies": [],
        "source": "manual_enrich_china"
    },

    # ═══════════ 八国联军侵华 (Boxer Rebellion, 1900) ═══════════
    {
        "id": next_id + 25,
        "name": "Battle of Tientsin",
        "war": "BOXER REBELLION",
        "warCn": "八国联军侵华",
        "sideA": "China",
        "sideB": "Eight-Nation Alliance",
        "latitude": 39.1333,
        "longitude": 117.2000,
        "date": "1900-06-17",
        "year": 1900,
        "winner": "defender",
        "region": "Asia",
        "country": "China",
        "attackerTroops": 20000,
        "defenderTroops": 8000,
        "totalTroops": 28000,
        "attackerCasualties": 5000,
        "defenderCasualties": 800,
        "totalCasualties": 5800,
        "casualtyRate": 0.2071,
        "terrain": "Urban, River",
        "weather": "Hot, Summer",
        "commanderA": "NI ECHENG",
        "commanderB": "ADNA CHAFFEE",
        "front": 10,
        "depth": 8,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Tientsin",
        "attackerAllies": [],
        "defenderAllies": ["United Kingdom", "United States", "France", "Germany", "Japan", "Russia"],
        "source": "manual_enrich_china"
    },
    {
        "id": next_id + 26,
        "name": "Battle of Peking",
        "war": "BOXER REBELLION",
        "warCn": "八国联军侵华",
        "sideA": "China",
        "sideB": "Eight-Nation Alliance",
        "latitude": 39.9042,
        "longitude": 116.4074,
        "date": "1900-08-14",
        "year": 1900,
        "winner": "defender",
        "region": "Asia",
        "country": "China",
        "attackerTroops": 100000,
        "defenderTroops": 18000,
        "totalTroops": 118000,
        "attackerCasualties": 8000,
        "defenderCasualties": 300,
        "totalCasualties": 8300,
        "casualtyRate": 0.0703,
        "terrain": "Urban, Siege",
        "weather": "Hot, Summer",
        "commanderA": "RONG LU",
        "commanderB": "ALFRED VON WALDERSEE",
        "front": 20,
        "depth": 15,
        "wikiUrl": "https://en.wikipedia.org/wiki/Battle_of_Peking_(1900)",
        "attackerAllies": [],
        "defenderAllies": ["United Kingdom", "United States", "France", "Germany", "Japan", "Russia", "Italy", "Austria"],
        "source": "manual_enrich_china"
    },
    {
        "id": next_id + 27,
        "name": "Siege of the International Legations",
        "war": "BOXER REBELLION",
        "warCn": "八国联军侵华",
        "sideA": "China",
        "sideB": "Eight-Nation Alliance",
        "latitude": 39.9046,
        "longitude": 116.4053,
        "date": "1900-06-20",
        "year": 1900,
        "winner": "defender",
        "region": "Asia",
        "country": "China",
        "attackerTroops": 20000,
        "defenderTroops": 500,
        "totalTroops": 20500,
        "attackerCasualties": 1000,
        "defenderCasualties": 65,
        "totalCasualties": 1065,
        "casualtyRate": 0.052,
        "terrain": "Urban, Siege",
        "weather": "Hot, Summer",
        "commanderA": "DONG FUXIANG",
        "commanderB": "CLAUDE MACDONALD",
        "front": 2,
        "depth": 1,
        "wikiUrl": "https://en.wikipedia.org/wiki/Siege_of_the_International_Legations",
        "attackerAllies": [],
        "defenderAllies": ["United Kingdom", "United States", "France", "Germany", "Japan", "Russia", "Italy", "Austria"],
        "source": "manual_enrich_china"
    },
]

# ============== Append and save ==============
existing_data.extend(china_battles)

# Ensure all events have required fields with defaults
for e in china_battles:
    for field in ['attackerAllies', 'defenderAllies']:
        if field not in e:
            e[field] = []
    for field in ['commanderA', 'commanderB']:
        if field not in e:
            e[field] = ''
    if 'front' not in e:
        e['front'] = 0
    if 'depth' not in e:
        e['depth'] = 0

with open(BATTLE_JSON, 'w', encoding='utf-8') as f:
    json.dump(existing_data, f, ensure_ascii=False, indent=2)

print(f"\nAdded {len(china_battles)} China battles")
print(f"Total battles now: {len(existing_data)}")

# Summary stats
total_deaths = sum(e['totalCasualties'] for e in china_battles)
total_troops = sum(e['totalTroops'] for e in china_battles)
print(f"\nNew China battles summary:")
print(f"  Total battles: {len(china_battles)}")
print(f"  Total deaths: {total_deaths:,}")
print(f"  Total troops: {total_troops:,}")
print(f"  Avg casualty rate: {(total_deaths/total_troops)*100:.1f}%")

# Group by war
wars = {}
for e in china_battles:
    w = e['warCn']
    if w not in wars:
        wars[w] = {'count': 0, 'deaths': 0}
    wars[w]['count'] += 1
    wars[w]['deaths'] += e['totalCasualties']

print("\nBy war:")
for war, stats in wars.items():
    print(f"  {war}: {stats['count']} battles, {stats['deaths']:,} deaths")

print("\nDone! File updated:", BATTLE_JSON)
